version: '3'

services:
  backend:
    build:
      context: ./expense_tracker_backend    # Path to your backend Dockerfile
    container_name: django_backend
    volumes:
      - ./expense_tracker_backend:/app      # Sync the backend code into the container
    ports:
      - "8000:8000"         # Expose Django on port 8000
    environment:
      - DJANGO_SETTINGS_MODULE=expense_tracker_backend.settings
      - DEBUG=True
      - SECRET_KEY=your-secret-key
      - ALLOWED_HOSTS=localhost,django_backend
    depends_on:
      - frontend            # Wait for frontend to start

  frontend:
    build:
      context: ./expense-tracker-frontend    # Path to your frontend Dockerfile
    container_name: nextjs_frontend
    volumes:
      - ./expense-tracker-frontend:/app      # Sync the frontend code into the container
    ports:
      - "3000:3000"          # Expose Next.js on port 3000